// <auto-generated />
namespace ComiteAgua.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PagoIdNull_Recibos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PagoIdNull_Recibos));
        
        string IMigrationMetadata.Id
        {
            get { return "201811291758388_PagoIdNull_Recibos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
